name: room_track_flutterapp
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.3
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  shimmer: ^3.0.0
  flutter_dotenv: ^5.2.1
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  path: ^1.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  google_maps_flutter: ^2.9.0
  location: ^6.0.2
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  share_plus: ^10.1.2

dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: 0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
  - assets/card/building.svg   
  - assets/card/computerlab.svg  
  - assets/background/logo.svg  
  - assets/button/outlook.svg       
  - assets/button/github.svg       
  - assets/button/search.svg          
  - assets/map/user.png
  - assets/card/classroom.svg  
  - assets/icon/icon.png         
  - assets/button/map.svg       
  - assets/placeholder/profile.png  
  - assets/background/server_off.svg  
  - assets/card/vertex.svg
  - assets/.env